name = "DataScienceTraits"
uuid = "6cb2f572-2d2b-4ba6-bdb3-e710fa044d6c"
authors = ["Elias Carvalho <eliascarvdev@gmail.com> and contributors"]
version = "0.2.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[weakdeps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
CoDa = "5900dafe-f573-5c72-b367-76665857777b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DynamicQuantities = "06fc5a27-2a28-4c7c-a15d-362465fb6821"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
DataScienceTraitsCategoricalArraysExt = "CategoricalArrays"
DataScienceTraitsCoDaExt = "CoDa"
DataScienceTraitsDistributionsExt = "Distributions"
DataScienceTraitsDynamicQuantitiesExt = "DynamicQuantities"
DataScienceTraitsMeshesExt = "Meshes"
DataScienceTraitsUnitfulExt = "Unitful"

[compat]
CategoricalArrays = "0.10"
CoDa = "1.2"
Dates = "1.9"
Distributions = "0.25"
DynamicQuantities = "0.7"
Meshes = "0.36"
Unitful = "1.17"
julia = "1.9"
